# This workflow is used to update the build status badge in the README file.
name: CI Workflow

on:
  push:
    branches:
      - 'release/next'
  pull_request:
    branches:
      - 'release/next'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package verify
